### ISSUE TITLE
[Suggestion] Close all buffers except current macro

### ISSUE THREAD

**Issue by MikhailKuzntsov1** [bezlant/dotfiles#1]
Try out this function for keeping buffers clean
`keymap("n", "<F7>", ":%bd |e# | bd#<cr> |'\"", opts) -- close all buffers except current & restore cursor position in current buffer`

**Comment by bezlant** [comment]
Why not use `:tabonly`?

**Comment by MikhailKuzntsov1** [comment]
Because these are not tabs, but buffers. I'm not sure, maybe tabonly will work for buffers too.

**Comment by bezlant** [comment]
My bad I thought this was about tabs for some reason. I will give it a try. I have been using `bufdo bd` previously.

**Comment by bezlant** [comment]
Thanks again! Added this to the last commit without the cursor restore (I have autocommands on BufEnter already that restores my cursor positon)
